import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import "./globals.css";



const geistMono = Inconsolata({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      suppressHydrationWarning
        className={` ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
